notifications:
  email: false

language: ruby
sudo: false
addons:
  chrome: stable
rvm:
  - 2.4
  - 2.3.3
  - 2.2

env:
 - "RAILS_VERSION=4.2.9"
 - "RAILS_VERSION=5.0.6"

before_install:
  - gem install bundler
